[workspace]
channels = ["conda-forge"] # https://prefix.dev/conda-forge
name = "ctranslate2-rs-workspace"
platforms = [
    { platform = "linux-64", cuda = "12.9" },
]
version = "0.4.0"
preview = ["pixi-build"]

[package]
name = "ctranslate2-rs"
version = "0.10.1"
homepage = "https://github.com/jkawamoto/ctranslate2-rs"
repository = "https://github.com/jkawamoto/ctranslate2-rs"

[package.build]
backend = { name = "pixi-build-rust", version = "*" }

[package.build.config]
compilers = ["rust", "c", "cxx"]

[tasks]
clean = "cargo clean -p ct2rs"
full-clean = "cargo clean"
check = "cargo check -p ct2rs"
build = "cargo build -p ct2rs"
build-release = "cargo build --release"
test = "cargo test -p ct2rs"

[tasks.cuda-dyn]
cmd = 'cargo build -p ct2rs --no-default-features -F "cuda,cuda-dynamic-loading,all-tokenizers,hub,ruy"'
default-environment = "platform-cuda-dyn"
env = { CARGO_TARGET_DIR = "target/cuda-dyn" }

[tasks.cuda-full]
cmd = 'cargo build -p ct2rs --no-default-features -F "cuda,all-tokenizers,hub,ruy"'
default-environment = "platform-cuda-full"
env = { CARGO_TARGET_DIR = "target/cuda-full" }

[tasks.whisper-dyn]
cmd = 'cargo build -p ct2rs --no-default-features -F "cuda,cuda-dynamic-loading,all-tokenizers,whisper,hub,ruy"'
default-environment = "platform-cuda-dyn"
env = { CARGO_TARGET_DIR = "target/whisper-dyn" }

[tasks.check-whisper-dyn]
cmd = 'cargo check -p ct2rs --no-default-features -F "cuda,cuda-dynamic-loading,all-tokenizers,whisper,hub,ruy"'
default-environment = "platform-cuda-dyn"
env = { CARGO_TARGET_DIR = "target/whisper-dyn" }

[tasks.flash-attn]
cmd = 'cargo build -p ct2rs --no-default-features -F "cuda,cuda-dynamic-loading,flash-attention,all-tokenizers,hub,ruy"'
default-environment = "platform-cuda-dyn"
env = { CUDA_ARCH_LIST = "8.9;9.0;10.0;12.0", CARGO_TARGET_DIR = "target/cuda-dyn" }

[tasks.doc]
cmd = "cargo rustdoc -F whisper,hub -p ct2rs"
default-environment = "hub"
env = { RUSTC_BOOTSTRAP = "1", RUSTDOCFLAGS = "--cfg docsrs" }

[tasks.doc-platform]
cmd = "cargo rustdoc -F whisper,hub -p ct2rs-platform"
default-environment = "platform"
env = { RUSTC_BOOTSTRAP = "1", RUSTDOCFLAGS = "--cfg docsrs" }

[tasks.build-vv]
cmd = 'cargo build -vv -p ct2rs --no-default-features -F "cuda,all-tokenizers,whisper,hub,ruy"'
default-environment = "platform-cuda-full"
env = { CMAKE_VERBOSE_MAKEFILE = "1", RUST_BACKTRACE = "full" }
# clean-env = true # ref: https://pixi.prefix.dev/latest/workspace/advanced_tasks/#clean-environment

[dependencies]
rust = "*"
rust-src = ">=1.98.1,<2"

compilers = ">=1.8.0"
cmake = ">=4.2.3,<5"
ninja = ">=1.13.2,<2"

sccache = ">=0.17.0,<0.18" # TODO we must configurate sccache ASAP!

[activation.env]
CFLAGS = "$CFLAGS -pthread"
CXXFLAGS = "$CXXFLAGS -pthread"
CMAKE_GENERATOR = "Ninja"

[environments]
default = []
# TODO this must be completed with all dependencies required by `ct2rs-platform`
platform = ["platform-cuda-dyn", "tensor-parallel", "hub"]
platform-cuda-dyn = ["platform-cuda-dyn", "hub"]
platform-cuda-full = ["platform-cuda-dyn", "platform-cuda-full", "hub"]
hub = ["hub"]

[feature.platform-cuda-dyn.dependencies]
cuda-version = "12.9.*"
cuda-nvcc = "*"
cuda-cudart-dev = "*"
libcurand-dev = "*"
libcublas-dev = "*"

[feature.platform-cuda-dyn.activation.env]
CUDA_ARCH_LIST = "Auto"
CUDA_TOOLKIT_ROOT_DIR = "$CONDA_PREFIX/targets/x86_64-linux"
CUDA_PATH = "$CONDA_PREFIX/targets/x86_64-linux"
PATH = "$CONDA_PREFIX/nvvm/bin:$PATH"

[feature.platform-cuda-full.dependencies]
cudnn = "8.*"
libcublas-static = "*"

[feature.tensor-parallel.dependencies]
openmpi = "*"
nccl = "*"

[feature.hub.dependencies]
openssl = ">=3.6.4,<4"
pkg-config = ">=0.29.2,<0.30"
